export KUBECONFIG=~/openshift/auth/kubeconfig
echo """apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nutanix-volume
provisioner: csi.nutanix.com
parameters:
  csi.storage.k8s.io/provisioner-secret-name: ntnx-secret
  csi.storage.k8s.io/provisioner-secret-namespace: ntnx-system
  csi.storage.k8s.io/node-publish-secret-name: ntnx-secret
  csi.storage.k8s.io/node-publish-secret-namespace: ntnx-system
  csi.storage.k8s.io/controller-expand-secret-name: ntnx-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: ntnx-system
  csi.storage.k8s.io/fstype: ext4
  dataServiceEndPoint: @@{DS_IP}@@:3260
  storageContainer: @@{PE_CONTAINER}@@
  storageType: NutanixVolumes
  #whitelistIPMode: ENABLED
  #chapAuth: ENABLED
allowVolumeExpansion: true
reclaimPolicy: Delete""" > storageclass.yaml
echo """kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: image-registry-claim
  namespace: openshift-image-registry
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: nutanix-volume""" > pvc.yaml

oc create -f storageclass.yaml
oc create -f pvc.yaml

# Patch OC Image Registry to use created PVC
oc patch configs.imageregistry.operator.openshift.io cluster --type merge --patch '{"spec":{"managementState":"Managed","storage":{"pvc":{"claim":"image-registry-claim"}},"rolloutStrategy": "Recreate"}}'

cat << EOF | oc apply -f -
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: image-registry-claim-1
  namespace: openshift-image-registry
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
storageClassName: nutanix-volume
EOF

sudo podman run -d \
   --name haproxy \
   -v /etc/haproxy:/usr/local/etc/haproxy:ro \
   -p 80:80 \
   -p 443:443 \
   -p 6443:6443 \
   -p 22623:22623 \
   -p 9000:9000 \
   -p 9999:9999 \
   public.ecr.aws/x0e4z5r2/haproxy-alpine:2.4
   
  cat << EOF | oc apply -f -
apiVersion: v1
kind: Secret
metadata:
  name: ntnx-secret
  namespace: ntnx-system
stringData:
  key: 10.38.4.7:9440:admin:nx2Tech823!
  # example: key: 10.38.4.7:9440:admin:nx2Tech823!
EOF

cat << EOF | oc apply -f -
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: nutanix-volume
provisioner: csi.nutanix.com
parameters:
  csi.storage.k8s.io/provisioner-secret-name: ntnx-secret
  csi.storage.k8s.io/provisioner-secret-namespace: ntnx-system
  csi.storage.k8s.io/node-publish-secret-name: ntnx-secret
  csi.storage.k8s.io/node-publish-secret-namespace: ntnx-system
  csi.storage.k8s.io/controller-expand-secret-name: ntnx-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: ntnx-system
  csi.storage.k8s.io/fstype: ext4
  dataServiceEndPoint: 10.38.4.8:3260
  # example:
  # dataServiceEndPoint: 10.38.5.72:3260
  storageContainer: Default
  # example:
  # storageContainer: Default
  storageType: NutanixVolumes
allowVolumeExpansion: true
reclaimPolicy: Delete
EOF